name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform Changes
      run: terraform plan -out=tfplan

    - name: Apply Terraform Changes
      run: terraform apply -auto-approve tfplan

    - name: Sync Static Files to S3
      run: |
        aws s3 sync ./website/ s3://tf-first-project --delete
        aws cloudfront create-invalidation --distribution-id E2Z5HJ64UUJ03X --paths "/*"
