name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Fail if the job takes longer than 30 minutes

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 5: Validate Terraform Configuration
      - name: Validate Terraform Configuration
        run: terraform validate

      # Step 6: Plan Terraform Changes
      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan

      # Step 7: Apply Terraform Changes
      - name: Apply Terraform Changes
        run: terraform apply -auto-approve tfplan

      # Step 8: Sync Static Files to S3
      - name: Sync Static Files to S3
        run: |
          aws s3 sync ./website/ s3://tf-first-project --delete

      # Step 9: Invalidate CloudFront Cache
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"